### ISSUE TITLE
Incorrect README for Holistic Bias

### ISSUE THREAD

**Issue by ysahil97** [facebookresearch/ResponsibleNLP#28]
This issue highlights the inaccuracy in the README for Holistic Bias dataset.
After installing all the requirements, the data generation script `holistic_bias/generate_sentences.py` doesn't work and gives the following error:
```
Traceback (most recent call last):
  File "/Path/to/ResponsibleNLP/holistic_bias/generate_sentences.py", line 11, in <module>
    from holistic_bias.src.sentences import HolisticBiasSentenceGenerator
ModuleNotFoundError: No module named 'holistic_bias'
```

This issue arises due to `holistic_bias` library being accessible only from ResponsibleNLP folder. We verified it by running python interpreter at this folder and it worked like a charm.

A possible fix for this issue is to have a copy/move `generate_sentences.py` to the `ResponsibleNLP` folder.

**Comment by EricMichaelSmith** [comment]
Clarified run folder with https://github.com/facebookresearch/ResponsibleNLP/pull/30

**Comment by hycern** [comment]
Hello, I am using Python 3.10 on Windows. The issue seems to still be there

```
(ResponsibleNLP) C:\Users\arjita\Documents\code\ResponsibleNLP>python holistic_bias\generate_sentences.py holistic_bias\arjita
Traceback (most recent call last):
  File "C:\Users\arjita\Documents\code\ResponsibleNLP\holistic_bias\generate_sentences.py", line 11, in <module>
    from holistic_bias.src.sentences import HolisticBiasSentenceGenerator
ModuleNotFoundError: No module named 'holistic_bias'
```

I had to change the import paths in two files, holistic_bias\generate_sentences.py
```python
from src.sentences import HolisticBiasSentenceGenerator
from src.util import DEFAULT_DATASET_VERSION
```

and holistic_bias\src\sentences.py
```python
from .util import NO_PREFERENCE_DATA_STRING, NONE_STRING, RANDOM_SEED
```
