### ISSUE TITLE
Error in generating AdvPrompt dataset

### ISSUE THREAD

**Issue by akanksha-2002** [facebookresearch/ResponsibleNLP#39]
While implementing the instructions provided in Advprompt to generate the dataset, the [command](https://github.com/facebookresearch/ResponsibleNLP/tree/main/AdvPromptSet#generating-the-dataset) of running main.py is giving the following error:

`(advpromptset) akankshabhimte@Akankshas-MacBook-Air ResponsibleNLP % python AdvPromptSet/main.py`
`usage: main.py [-h] data`
`main.py: error: the following arguments are required: data`

What should I put in the argument?

**Comment by EricMichaelSmith** [comment]
Pinging @davides

**Comment by ellenxtan** [comment]
Fixed in this PR: https://github.com/facebookresearch/ResponsibleNLP/pull/45 . Thanks
