### ISSUE TITLE
Different CrowS-Pairs scores for Roberta large than the ones reported in the CrowS-Pairs  paper.

### ISSUE THREAD

**Issue by efatmae** [facebookresearch/ResponsibleNLP#4]
Hi,

I've read you paper and noticed that the CrowS-Pairs scores for Roberta large (RoBERTA- 160GB) is different from the scores reported in the Crows-pair paper where they used Robeta-large through Hugging-Face interface.

I also ran the CrowS-Pairs code on Roberta-base (through Hugging-face) and the bias scores are different from the ones you report in your paper for RoBERTa (16GB).

Do you know why this might be the case? Do you also use the models through Hugging-face or not? Can you release the code used to measure the bias scores?

Best,
Fatma

**Comment by Rebecca-Qian** [comment]
Hi @efatmae, thanks for reaching out. We do not report statistics on RoBERTa-large in our paper - the model you are referring to is RoBERTa-base, which you can access through HuggingFace. The RoBERTa-base model is a 12 layer architecture trained on 160GB data. We were able to reproduce the results reported in the CrowS-Pairs paper.

The 16GB model you are referring to is a model we trained on the BookWiki corpus (16GB), which we use for ablation studies. We will be releasing the models we trained through github and HuggingFace very soon, as well as code to measure bias.

Hope this is helpful!

**Comment by Rebecca-Qian** [comment]
Hi @efatmae, apologies for the confusion. Have you seen this warning posted on the CrowS-pairs repo?

> Note that, if you use a newer version of transformers (3.x.x), you might obtain different scores than the one reported in our paper.

We are using transformers version 4.16.2. The CrowS results are obtained using the same script from the CrowS-pairs repo.

**Comment by efatmae** [comment]
Hi @Rebecca-Qian,

Thanks for your reply and for pointing our this note from crowS-Pairs repo about the transformers version. Do you know why this might be the case? why different Transformers version produce different results?

and Just to be clear, you use RoBERTa large like in the crowS-Pair paper, right?

Best,
Fatma

**Comment by Rebecca-Qian** [comment]
@efatmae in the older transformers version each input is prepended with a single space before tokenization. This discrepancy is also mentioned in this paper: https://arxiv.org/pdf/2103.00453.pdf

Using our transformers version for RoBERTa-large we get the same CrowS scores for RoBERTa-large as the Schick et al. paper. The comparisons in the paper are all made on models with the RoBERTa-base architecture, i.e. 12 layers.
